name: 'snowflake_dbt'
version: '1.0.0'
profile: 'snowflake'
config-version: 2

macro-paths: ["macros"] 

models:
  snowflake_dbt:
    raw:
      +materialized: table
      +schema: STAGGING
    dim:
      +materialized: table
      +schema: DIM 
    fact:
      +materialized: table
      +schema: FACT 
    marts:
      +materialized: view
      +schema: AGGR 