CREATE TABLE RAW.ORDERS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES RAW.CUSTOMERS(ID),
    MENU_ITEM_ID NUMBER REFERENCES RAW.MENU_ITEMS(ID),
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10, 2),
    ORDER_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);