CREATE TABLE raw.orders (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES raw.customers(ID),
    MENU_ITEM_ID NUMBER REFERENCES raw.menu_items(ID),
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10, 2),
    ORDER_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);