{{ config(materialized='view') }}

SELECT
    DATE_TRUNC('month', ORDER_DATE) AS MONTH,
    CATEGORY,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM {{ ref('fact_orders') }}
GROUP BY DATE_TRUNC('month', ORDER_DATE), CATEGORY